# Ma'lumotlar bazasi konfiguratsiyasi (PostgreSQL uchun)
spring.datasource.url=jdbc:postgresql://localhost:5432/chat_db
spring.datasource.username=postgres
spring.datasource.password=aziz0000
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA konfiguratsiyasi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# WebSocket uchun (agar kerak bo'lsa)
server.port=8080
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Security konfiguratsiyasi (ixtiyoriy)
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false